name: laravel-ci

on:
  push:
    branches:
      # - "master"
      # - "main"
      - "develop"

jobs:
  laravel-php74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Login to Darknamer Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: hub.darknamer.xyz
      #     username: darknamer
      #     password: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build ubuntu os with focal
      - name: Ubuntu Build & push
        uses: docker/build-push-action@v2
        with:
          context: containers/laravel/mains/7.4
          file: ./containers/laravel/mains/7.4/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            unnamed22090/laravel:7.4

  laravel-php80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Login to Darknamer Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: hub.darknamer.xyz
      #     username: darknamer
      #     password: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build ubuntu os with focal
      - name: Ubuntu Build & push
        uses: docker/build-push-action@v2
        with:
          context: ./containers/laravel/mains/8.0
          file: ./containers/laravel/mains/8.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            unnamed22090/laravel
            unnamed22090/laravel:8.0