name: ubuntu-cmd

on:
  push:
    branches:
      - "master"
      - "main"
  # schedule:
  #   - cron:  '0 5 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Darknamer Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: hub.darknamer.xyz
      #     username: darknamer
      #     password: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build ubuntu os with focal
      - name: Ubuntu Build & push (focal)
        uses: docker/build-push-action@v2
        with:
          context: ./containers/ubuntu/cmd/focal
          file: ./containers/ubuntu/cmd/focal/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            unnamed22090/ubuntu:cmd-focal
            unnamed22090/ubuntu:cmd-20.04

      # build ubuntu os with jammy
      - name: Ubuntu Build & push (jammy)
        uses: docker/build-push-action@v2
        with:
          context: ./containers/ubuntu/cmd/jammy
          file: ./containers/ubuntu/cmd/jammy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            unnamed22090/ubuntu:cmd-jammy
            unnamed22090/ubuntu:cmd-22.04